apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
data:
  POSTGRES_USER: {{ .Values.postgresql.global.postgresql.auth.username }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.global.postgresql.auth.password }}
  DATABASE_HOST: "{{ .Release.Name }}-postgresql-hl"
  PORT: "5432"
  POSTGRES_DB: {{ .Values.postgresql.global.postgresql.auth.database }}
  NATS_URL: "{{ .Release.Name }}-nats"